name: build kernel with my own flavor (Magic KSU + Scoped Hook + SUSFS + WireGuard)

on:
  schedule:
    - cron: "0 0 * * 5"
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout script
        uses: actions/checkout@v4
      
      - name: run build script
        run: |
          chmod +x build.sh
          bash build.sh --wireguard --scoped-hook --with-susfs
          
      - name: upload kernel 
        uses: actions/upload-artifact@v4
        with:
          name: release-kernel
          path: |
            AnyKernel3/*
